station_links = {
    "FRANCONIA-SPRINGF'LD": 'Franconia-Springfield',
    'VIRGINIA SQUARE | GMU': 'Virginia Square-GMU',
    'GROSVENOR-STRATHMORE': 'Grosvenor-Strathmore',
    'DUPONT CIRCLE': 'Dupont Circle',
    'BALLSTON': 'Ballston',
    'CLARENDON': 'Clarendon',
    'CLARENDON': 'Clarendon',
    'BENNING ROAD': 'Benning Road',
    'COURT HOUSE': 'Court House',
    'COURT HOUSE': 'Court House',
    'DUNN LORING': 'Dunn Loring',
    'VIENNA | FAIRFAX-GMU': 'Vienna',
    'BROOKLAND | CUA': 'Brookland-CUA',
    'CAPITOL HEIGHTS': 'Capitol Heights',
    'ADDISON ROAD | SEAT PLEASANT': 'Addison Road',
    'FORT TOTTEN': 'Fort Totten',
    'ANACOSTIA': 'Anacostia',
    'CONGRESS HEIGHTS': 'Congress Heights',
    'SOUTHERN AVE': 'Southern Ave',
    'NAYLOR ROAD': 'Naylor Road',
    'BENNING ROAD': 'Benning Road',
    'CAPITOL HEIGHTS': 'Capitol Heights',
    'GREENSBORO': 'Greensboro',
    'GREENSBORO': 'Greensboro',
    'W FALLS CHURVH | VT | UVA': 'West Falls Church',
    'CHEVERLY': 'Cheverly',
    'MINNESOTA AVE': 'Minnesota Ave',
    'PENTAGON': 'Pentagon',
    'EISENHOWER AVENUE': 'Eisenhower Avenue',
    'HUNTINGTON': 'Huntington',
    'KING STREET': 'King Street',
    'COLUMBIA HEIGHTS': 'Columbia Heights',
    'CHEVERLY': 'Cheverly',
    'COLLEGE PARK': 'College Park-U of Md',
    'MORGAN BOULEVARD': 'Morgan Boulevard',
    'CONGRESS HEIGHTS': 'Congress Heights',
    'DEANWOOD': 'Deanwood',
    'FEDERAL CENTER SW': 'Federal Center SW',
    'FOREST GLEN': 'Forest Glen',
    'GLENMONT': 'Glenmont',
    'GLENMONT': 'Glenmont',
    'MINNESOTA AVE': 'Minnesota Ave',
    'NAVY YARD-BALLPARK': 'Navy Yard-Ballpark',
    'SHAW | HOWARD UNIV': 'Shaw-Howard Univ',
    'U ST | AFRICAN AMER CIVIL WAR MEM | CARDOZO ELEV': 'U Street',
    'VAN DORN ST': 'Van Dorn Street',
    'VIRGINIA SQUARE | GMU': 'Virginia Square-GMU',
    'WATERFRONT': 'Waterfront',
    'NEW CARROLLTON': 'New Carrollton',
    'GEORGIA AVE | PETWORTH': 'Georgia Ave-Petworth',
    'GEORGIA AVE | PETWORTH': 'Georgia Ave-Petworth',
    'BROOKLAND | CUA': 'Brookland-CUA',
    'TYSONS CORNER': 'Tysons Corner',
    'NOMA | GALLAUDET U | NEW YORK AVE': 'NoMa-Gallaudet U',
    'JUDICIARY SQUARE NE': 'Judiciary Square',
    'JUDICIARY SQUARE SW': 'Judiciary Square',
    'EASTERN MARKET': 'Eastern Market',
    'SPRING HILL': 'Spring Hill',
    'WIEHLE | RESTON EAST': 'Wiehle-Reston'}


# Create a list of metro station names per line
blue_line_stations = [
    "FRANCONIA-SPRINGF'LD",
    "VAN DORN ST",
    "KING STREET",
    "BRADDOCK ROAD",
    "RONALD REAGAN WASHINGTON NATIONAL AIRPORT",
    "CRYSTAL CITY",
    "PENTAGON CITY",
    "PENTAGON",
    "ARLINGTON CEMETERY",
    "ROSSLYN",
    "FOGGY BOTTOM | GWU",
    "FARRAGUT WEST",
    "MCPHERSON SQUARE",
    "METRO CENTER",
    "FEDERAL TRIANGLE",
    "SMITHSONIAN",
    "L'ENFANT PLAZA",
    "FEDERAL CENTER SW",
    "CAPITOL SOUTH",
    "EASTERN MARKET",
    "POTOMAC AVE",
    "STADIUM | ARMORY",
    "BENNING ROAD",
    "CAPITOL HEIGHTS",
    "ADDISON ROAD | SEAT PLEASANT",
    "MORGAN BOULEVARD",
    "LARGO TOWN CENTER"
]

orange_line_stations =  [
    "VIENNA | FAIRFAX-GMU",
    "DUNN LORING",
    "W FALLS CHURVH | VT | UVA",
    "W FALLS CHURVH | VT | UVA",
    "BALLSTON",
    "VIRGINIA SQUARE",
    "CLARENDON",
    "COURT HOUSE",
    "ROSSLYN",
    "FOGGY BOTTOM",
    "FARRAGUT WEST",
    "MCPHERSON SQUARE",
    "METRO CENTER",
    "FEDERAL TRIANGLE",
    "SMITHSONIAN",
    "L'ENFANT",
    "FEDERAL CENTER",
    "CAPITOL SOUTH",
    "EASTERN MARKET",
    "POTOMAC AVE",
    "STADIUM-ARMORY",
    "MINNESOTA AVE",
    "DEANWOOD",
    "CHEVERLY",
    "LANDOVER",
    "NEW CARROLLTON"
]

silver_line_stations = [
    "WIEHLE | RESTON EAST",
    "SPRINGHILL",
    "GREENSBORO",
    "TYSONS CORNER",
    "MCLEAN",
    "E FALLS CHURCH",
    "BALLSTON",
    "VIRGINIA SQUARE | GMU",
    "CLARENDON",
    "COURT HOUSE",
    "ROSSLYN",
    "FOGGY BOTTOM | GWU",
    "FARRAGUT WEST",
    "MCPHERSON SQUARE",
    "METRO CENTER",
    "FEDERAL TRIANGLE",
    "SMITHSONIAN",
    "L'ENFANT PLAZA",
    "FEDERAL CENTER SW",
    "CAPITOL SOUTH",
    "EASTERN MARKET",
    "POTOMAC AVE",
    "STADIUM | ARMORY",
    "BENNING ROAD",
    "CAPITOL HEIGHTS",
    "ADDISON ROAD | SEAT PLEASANT",
    "MORGAN BOULEVARD",
    "LARGO TOWN CENTER"
]

red_line_stations = [
    "SHADY GROVE",
    "ROCKVILLE",
    "TWINBROOK",
    "WHITE FLINT",
    "GROSVENOR-STRATHMORE",
    "MEDICAL CENTER",
    "BETHESDA",
    "FRIENDSHIP HEIGHTS",
    "TENLEYTOWN | AU",
    "VAN NESS | UDC",
    "CLEVELAND PARK",
    "WOODLEY PARK | ZOO | ADAMS MORGAN",
    "DUPONT CIRCLE",
    "FARRAGUT NORTH",
    "METRO CENTER",
    "GALLERY PL | CHINATOWN",
    "JUDICIARY SQUARE",
    "UNION STATION",
    "NOMA | GALLAUDET U | NEW YORK AVE",
    "RHODE ISLAND AVE | BRENTWOOD",
    "BROOKLAND | CUA",
    "FORT TOTTEN",
    "TAKOMA",
    "SILVER SPRING",
    "FOREST GLEN",
    "GLENMONT"
]

green_line_stations =  [
    "GREENBELT",
    "COLLEGE PARK",
    "PRINCE GEORGES PLAZA",
    "WEST HYATTSVILLE",
    "FORT TOTTEN",
    "GEORGIA AVE | PETWORTH",
    "COLUMBIA HEIGHTS",
    "U ST | AFRICAN AMER CIVIL WAR MEM | CARDOZO",
    "SHAW | HOWARD UNIV",
    "MT VERNON SQ | 7TH ST | CONVENTION CENTER",
    "GALLERY PL",
    "ARCHIVES | NAVY MEM | PENN QUARTER",
    "L'ENFANT",
    "WATERFRONT",
    "NAVY YARD-BALLPARK",
    "ANACOSTIA",
    "CONGRESS HEIGHTS",
    "SOUTHERN AVE",
    "NAYLOR ROAD",
    "SUITLAND",
    "BRANCH AVENUE"
]

yellow_line_stations = [
    "FORT TOTTEN",
    "GEORGIA AVE | PETWORTH",
    "COLUMBIA HEIGHTS",
    "U ST | AFRICAN AMER CIVIL WAR MEM | CARDOZO ELEV",
    "SHAW | HOWARD UNIV",
    "MT VERNON SQ | 7TH ST | CONVENTION CENTER",
    "GALLERY PLACE",
    "ARCHIVES | NAVY MEM | PENN QUARTER",
    "L'ENFANT",
    "PENTAGON",
    "CRYSTAL CITY",
    "REAGAN",
    "BRADDOCK ROAD",
    "KING STREET",
    "EISENHOWER AVENUE",
    "HUNTINGTON"
]

# Create a dictionary to map line names to their corresponding station lists
line_station_map = {
    'blue': blue_line_stations,
    'orange': orange_line_stations,
    'silver': silver_line_stations,
    'red': red_line_stations,
    'green': green_line_stations,
    'yellow': yellow_line_stations
}

line_colors = {
    'blue': 'blue',
    'orange': 'orange',
    'silver': '#C0C0C0',  # Hex code for silver
    'red': 'red',
    'green': 'green',
    'yellow': 'yellow'
}

# Create a dictionary to map stations to their corresponding lines
station_lines = {}
for line, stations in line_station_map.items():
    for station in stations:
        station_lines.setdefault(station, []).append(line)
