station_links = {
    "FRANCONIA-SPRINGF'LD": 'Franconia-Springfield',
    'VIRGINIA SQUARE | GMU ELEVATOR': 'Virginia Square-GMU',
    'GROSVENOR-STRATHMORE': 'Grosvenor-Strathmore',
    'DUPONT CIRCLE': 'Dupont Circle',
    'BALLSTON ELEVATOR': 'Ballston',
    'CLARENDON': 'Clarendon',
    'CLARENDON ELEVATOR': 'Clarendon',
    'BENNING ROAD ELEVATOR': 'Benning Road',
    'COURT HOUSE ELEVATOR': 'Court House',
    'COURT HOUSE': 'Court House',
    'DUNN LORING': 'Dunn Loring',
    'VIENNA | FAIRFAX-GMU': 'Vienna',
    'BROOKLAND | CUA': 'Brookland-CUA',
    'CAPITOL HEIGHTS ELEVATOR': 'Capitol Heights',
    'ADDISON ROAD | SEAT PLEASANT': 'Addison Road',
    'FORT TOTTEN': 'Fort Totten',
    'ANACOSTIA': 'Anacostia',
    'CONGRESS HEIGHTS': 'Congress Heights',
    'SOUTHERN AVE': 'Southern Ave',
    'NAYLOR ROAD': 'Naylor Road',
    'BENNING ROAD': 'Benning Road',
    'CAPITOL HEIGHTS': 'Capitol Heights',
    'GREENSBORO': 'Greensboro',
    'GREENSBORO ELEVATOR': 'Greensboro',
    'W FALLS CHURVH | VT | UVA': 'West Falls Church',
    'CHEVERLY ELEVATOR': 'Cheverly',
    'MINNESOTA AVE': 'Minnesota Ave',
    'PENTAGON': 'Pentagon',
    'EISENHOWER AVENUE': 'Eisenhower Avenue',
    'HUNTINGTON': 'Huntington',
    'KING STREET': 'King Street',
    'COLUMBIA HEIGHTS ELEVATOR': 'Columbia Heights',
    'CHEVERLY': 'Cheverly',
    'COLLEGE PARK ELEVATOR': 'College Park-U of Md',
    'MORGAN BOULEVARD': 'Morgan Boulevard',
    'CONGRESS HEIGHTS ELEVATOR': 'Congress Heights',
    'DEANWOOD ELEVATOR': 'Deanwood',
    'FEDERAL CENTER SW ELEVATOR': 'Federal Center SW',
    'FOREST GLEN': 'Forest Glen',
    'GLENMONT': 'Glenmont',
    'GLENMONT ELEVATOR': 'Glenmont',
    'MINNESOTA AVE ELEVATOR': 'Minnesota Ave',
    'NAVY YARD-BALLPARK ELEVATOR': 'Navy Yard-Ballpark',
    'SHAW | HOWARD UNIV ELEVATOR': 'Shaw-Howard Univ',
    'U ST | AFRICAN AMER CIVIL WAR MEM | CARDOZO ELEV': 'U Street',
    'VAN DORN ST': 'Van Dorn Street',
    'VIRGINIA SQUARE | GMU': 'Virginia Square-GMU',
    'WATERFRONT ELEVATOR': 'Waterfront',
    'NEW CARROLLTON': 'New Carrollton',
    'GEORGIA AVE | PETWORTH': 'Georgia Ave-Petworth',
    'GEORGIA AVE | PETWORTH ELEVATOR': 'Georgia Ave-Petworth',
    'BROOKLAND | CUA ELEVATOR': 'Brookland-CUA',
    'TYSONS CORNER ELEVATOR': 'Tysons Corner',
    'NOMA | GALLAUDET U | NEW YORK AVE': 'NoMa-Gallaudet U',
    'JUDICIARY SQUARE NE ELEVATOR': 'Judiciary Square',
    'JUDICIARY SQUARE SW ELEVATOR': 'Judiciary Square',
    'EASTERN MARKET': 'Eastern Market',
    'SPRING HILL ELEVATOR': 'Spring Hill',
    'WIEHLE | RESTON EAST ELEVATOR': 'Wiehle-Reston'}


# Create a list of metro station names per line
blue_line_stations = [
    "FRANCONIA-SPRINGF'LD",
    "VAN DORN ST",
    "KING STREET",
    "BRADDOCK ROAD",
    "RONALD REAGAN WASHINGTON NATIONAL AIRPORT",
    "CRYSTAL CITY",
    "PENTAGON CITY",
    "PENTAGON",
    "ARLINGTON CEMETERY",
    "ROSSLYN",
    "FOGGY BOTTOM | GWU",
    "FARRAGUT WEST",
    "MCPHERSON SQUARE",
    "METRO CENTER",
    "FEDERAL TRIANGLE",
    "SMITHSONIAN",
    "L'ENFANT PLAZA",
    "FEDERAL CENTER SW",
    "CAPITOL SOUTH",
    "EASTERN MARKET",
    "POTOMAC AVE",
    "STADIUM | ARMORY",
    "BENNING ROAD",
    "CAPITOL HEIGHTS",
    "ADDISON ROAD | SEAT PLEASANT",
    "MORGAN BOULEVARD",
    "LARGO TOWN CENTER"
]

orange_line_stations =  [
    "VIENNA",
    "DUNN LORING",
    "WEST FALLS CHURCH",
    "EAST FALLS CHURCH",
    "BALLSTON",
    "VIRGINIA SQUARE",
    "CLARENDON",
    "COURT HOUSE",
    "ROSSLYN",
    "FOGGY BOTTOM",
    "FARRAGUT WEST",
    "MCPHERSON SQUARE",
    "METRO CENTER",
    "FEDERAL TRIANGLE",
    "SMITHSONIAN",
    "L'ENFANT",
    "FEDERAL CENTER",
    "CAPITOL SOUTH",
    "EASTERN MARKET",
    "POTOMAC AVE",
    "STADIUM-ARMORY",
    "MINNESOTA AVE",
    "DEANWOOD",
    "CHEVERLY",
    "LANDOVER",
    "NEW CARROLLTON"
]

silver_line_stations = [
    "WIEHLE | RESTON EAST",
    "SPRINGHILL",
    "GREENSBORO",
    "TYSONS CORNER",
    "MCLEAN",
    "EAST FALLS CHURCH",
    "BALLSTON",
    "VIRGINIA SQUARE | GMU ELEVATOR",
    "CLARENDON",
    "COURT HOUSE",
    "ROSSLYN",
    "FOGGY BOTTOM | GWU ELEVATOR",
    "FARRAGUT WEST",
    "MCPHERSON SQUARE ELEVATOR",
    "METRO CENTER",
    "FEDERAL TRIANGLE ELEVATOR",
    "SMITHSONIAN",
    "L'ENFANT PLAZA",
    "FEDERAL CENTER SW ELEVATOR",
    "CAPITOL SOUTH",
    "EASTERN MARKET",
    "POTOMAC AVE",
    "STADIUM | ARMORY",
    "BENNING ROAD ELEVATOR",
    "CAPITOL HEIGHTS ELEVATOR",
    "ADDISON ROAD | SEAT PLEASANT",
    "MORGAN BOULEVARD",
    "LARGO TOWN CENTER"
]

red_line_stations = [
    "SHADY GROVE",
    "ROCKVILLE",
    "TWINBROOK",
    "WHITE FLINT",
    "GROSVENOR-STRATHMORE",
    "MEDICAL CENTER",
    "BETHESDA",
    "FRIENDSHIP HEIGHTS",
    "TENLEYTOWN",
    "VAN NESS",
    "CLEVELAND PARK",
    "WOODLEY PARK | ZOO | ADAMS MORGAN",
    "DUPONT CIRCLE",
    "FARRAGUT NORTH",
    "METRO CENTER",
    "GALLERY PL | CHINATOWN",
    "JUDICIARY SQUARE",
    "UNION STATION",
    "NOMA | GALLAUDET U | NEW YORK AVE",
    "RHODE ISLAND AVE | BRENTWOOD",
    "BROOKLAND | CUA",
    "FORT TOTTEN",
    "TAKOMA",
    "SILVER SPRING",
    "FOREST GLEN",
    "GLENMONT"
]

green_line_stations =  [
    "GREENBELT",
    "COLLEGE PARK",
    "PRINCE GEORGE'S PLAZA",
    "WEST HYATTSVILLE",
    "FORT TOTTEN",
    "GEORGIA AVE",
    "COLUMBIA HEIGHTS",
    "U ST",
    "SHAW-HOWARD",
    "MT VERNON SQ",
    "GALLERY PL",
    "ARCHIVES",
    "L'ENFANT",
    "WATERFRONT",
    "NAVY YARD",
    "ANACOSTIA",
    "CONGRESS HEIGHTS",
    "SOUTHERN AVE",
    "NAYLOR ROAD",
    "SUITLAND",
    "BRANCH AVE"
]

yellow_line_stations = [
    "FORT TOTTEN",
    "GEORGIA AVENUE",
    "COLUMBIA HEIGHTS",
    "U STREET",
    "SHAW-HOWARD",
    "MT VERNON SQUARE",
    "GALLERY PLACE",
    "ARCHIVES",
    "L'ENFANT",
    "PENTAGON",
    "CRYSTAL CITY",
    "REAGAN",
    "BRADDOCK ROAD",
    "KING STREET",
    "EISENHOWER AVENUE",
    "HUNTINGTON"
]

# Create a dictionary to map line names to their corresponding station lists
line_station_map = {
    'blue': blue_line_stations,
    'orange': orange_line_stations,
    'silver': silver_line_stations,
    'red': red_line_stations,
    'green': green_line_stations,
    'yellow': yellow_line_stations
}

line_colors = {
    'blue': 'blue',
    'orange': 'orange',
    'silver': '#C0C0C0',  # Hex code for silver
    'red': 'red',
    'green': 'green',
    'yellow': 'yellow'
}

# Create a dictionary to map stations to their corresponding lines
station_lines = {}
for line, stations in line_station_map.items():
    for station in stations:
        station_lines.setdefault(station, []).append(line)
